workflows:
  ios-release:
    name: iOS Release Workflow
    environment:
      flutter: stable # Use stable Flutter channel
      xcode: latest   # Use the latest Xcode version
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios && pod install && cd ..

      - name: Build iOS App
        script: flutter build ipa --release --no-tree-shake-icons

    artifacts:
      - build/ios/ipa/*.ipa # Path to the .ipa file to be saved
