workflows:
  ios-release:
    name: iOS Release Workflow
    environment:
      flutter: stable # Use the stable Flutter version or specify a version
      xcode: latest # Use the latest Xcode version
      cocoapods: default
      variables:
        PROJECT_NAME: "mitti_bot" # Replace with your actual project name if necessary
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios && pod install && cd ..

      - name: Build iOS App
        script: |
          flutter build ipa --release --no-tree-shake-icons

      - name: Save .ipa Artifact
        script: |
          mkdir -p build/ios/ipa
          cp build/ios/ipa/*.ipa $CM_BUILD_DIR

    artifacts:
      - build/ios/ipa/*.ipa # Save the generated .ipa file
